---
- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: add firewalld rule http
  firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled

- name: start httpd
  service: 
    name: httpd
    enabled: yes 
    state: started

- name: start firewalld
  service: 
    name: firewalld
    enabled: yes 
    state: restarted


